export type CompliancePhrase = {
  id: string
  riskPhrase: string
  recommendedPhrase: string
  riskLevel: 'low' | 'medium' | 'high'
  category: 'product' | 'income' | 'case' | 'company' | 'medical'
  reason: string
  exampleScenario: string
}

export const compliancePhrasebook: CompliancePhrase[] = [
  {
    id: 'medical-1',
    riskPhrase: '治疗疾病',
    recommendedPhrase: '支持健康管理',
    riskLevel: 'high',
    category: 'medical',
    reason: '直接触碰医疗治疗承诺，属于高风险表达。',
    exampleScenario: '介绍产品时描述适用方向。',
  },
  {
    id: 'medical-2',
    riskPhrase: '治愈',
    recommendedPhrase: '帮助改善状态感受',
    riskLevel: 'high',
    category: 'medical',
    reason: '“治愈”属于明确疗效结果承诺，禁止正向宣传使用。',
    exampleScenario: '分享个人感受或案例时。',
  },
  {
    id: 'medical-3',
    riskPhrase: '根治',
    recommendedPhrase: '不做疾病相关效果承诺',
    riskLevel: 'high',
    category: 'medical',
    reason: '暗示完全解决疾病问题，超出健康管理表达范围。',
    exampleScenario: '回应对方关于慢性问题的提问时。',
  },
  {
    id: 'medical-4',
    riskPhrase: '替代药物',
    recommendedPhrase: '不替代医疗建议，建议结合专业意见理解',
    riskLevel: 'high',
    category: 'medical',
    reason: '替代药物属于明显违规医疗暗示。',
    exampleScenario: '对方问能否停药或替换方案时。',
  },
  {
    id: 'medical-5',
    riskPhrase: '饿死癌细胞',
    recommendedPhrase: '支持细胞环境健康管理，不涉及疾病治疗',
    riskLevel: 'high',
    category: 'medical',
    reason: '直接指向癌症治疗语境，风险极高。',
    exampleScenario: '介绍 GnCELL 的科学背景时。',
  },
  {
    id: 'medical-6',
    riskPhrase: '肿瘤缩小',
    recommendedPhrase: '不做疾病相关效果承诺',
    riskLevel: 'high',
    category: 'medical',
    reason: '属于明确疾病结果承诺。',
    exampleScenario: '谈病例或转发案例时。',
  },
  {
    id: 'product-1',
    riskPhrase: '保证有效',
    recommendedPhrase: '体验因人而异，建议持续观察记录',
    riskLevel: 'high',
    category: 'product',
    reason: '绝对化效果承诺，无法验证且违规。',
    exampleScenario: '介绍产品使用预期时。',
  },
  {
    id: 'product-2',
    riskPhrase: '吃了就有效',
    recommendedPhrase: '建议持续体验并记录个人感受',
    riskLevel: 'high',
    category: 'product',
    reason: '暗示即时结果且适用于所有人。',
    exampleScenario: '回应产品见效时间时。',
  },
  {
    id: 'product-3',
    riskPhrase: '白发转黑',
    recommendedPhrase: '有用户反馈状态改善，但体验因人而异',
    riskLevel: 'high',
    category: 'product',
    reason: '容易被理解为明确外观效果承诺。',
    exampleScenario: '分享个人变化或转发反馈时。',
  },
  {
    id: 'product-4',
    riskPhrase: '血压正常',
    recommendedPhrase: '支持健康生活方式管理，不替代医疗建议',
    riskLevel: 'high',
    category: 'product',
    reason: '直接指向医学指标结果承诺。',
    exampleScenario: '介绍健康管理方向时。',
  },
  {
    id: 'product-5',
    riskPhrase: '逆转年龄',
    recommendedPhrase: '支持健康衰老和年轻态管理',
    riskLevel: 'medium',
    category: 'product',
    reason: '容易被理解为绝对化年龄结果，需要降级为管理方向。',
    exampleScenario: '概括产品方向时。',
  },
  {
    id: 'product-6',
    riskPhrase: '几天就能看到明显变化',
    recommendedPhrase: '每个人体验节奏不同，建议先持续观察',
    riskLevel: 'medium',
    category: 'product',
    reason: '暗示统一且快速结果。',
    exampleScenario: '谈体验周期时。',
  },
  {
    id: 'income-1',
    riskPhrase: '稳赚不赔',
    recommendedPhrase: '结果取决于个人努力、学习投入和市场行为',
    riskLevel: 'high',
    category: 'income',
    reason: '属于收益保证承诺，绝对禁止。',
    exampleScenario: '说明平台经营路径时。',
  },
  {
    id: 'income-2',
    riskPhrase: '一定赚钱',
    recommendedPhrase: '是否适合继续深入，要看个人投入和行动',
    riskLevel: 'high',
    category: 'income',
    reason: '直接承诺收入结果。',
    exampleScenario: '回应对方问收入可能性时。',
  },
  {
    id: 'income-3',
    riskPhrase: '零风险',
    recommendedPhrase: '轻资产、低门槛、从自用和学习开始',
    riskLevel: 'high',
    category: 'income',
    reason: '“零风险”是绝对化商业承诺，容易误导。',
    exampleScenario: '介绍平台门槛时。',
  },
  {
    id: 'income-4',
    riskPhrase: '月入过万很简单',
    recommendedPhrase: '成长需要时间、学习和持续行动',
    riskLevel: 'high',
    category: 'income',
    reason: '夸大速度与收益结果。',
    exampleScenario: '分享事业可能性时。',
  },
  {
    id: 'income-5',
    riskPhrase: '听完就知道能赚钱',
    recommendedPhrase: '先听懂路径，再判断是否适合自己',
    riskLevel: 'high',
    category: 'income',
    reason: '把会议内容直接导向收益结果。',
    exampleScenario: '邀请参加说明会时。',
  },
  {
    id: 'case-1',
    riskPhrase: '别人有效，你也一样会有效',
    recommendedPhrase: '别人的案例只能作参考，体验因人而异',
    riskLevel: 'high',
    category: 'case',
    reason: '把个案包装成普遍结果，风险很高。',
    exampleScenario: '转发案例或检测报告时。',
  },
  {
    id: 'case-2',
    riskPhrase: '这个案例说明产品肯定有用',
    recommendedPhrase: '这个案例仅供参考，建议结合资料和个人体验理解',
    riskLevel: 'medium',
    category: 'case',
    reason: '案例只能作为个体反馈，不能代替普遍证明。',
    exampleScenario: '讲解见证案例时。',
  },
  {
    id: 'case-3',
    riskPhrase: '我的变化你也能复制',
    recommendedPhrase: '我的感受只代表我自己，建议你先体验再判断',
    riskLevel: 'medium',
    category: 'case',
    reason: '暗示别人一定获得同样结果。',
    exampleScenario: '分享自用体验时。',
  },
  {
    id: 'company-1',
    riskPhrase: '加入就能成功',
    recommendedPhrase: '加入后仍需要持续学习、行动和复盘',
    riskLevel: 'high',
    category: 'company',
    reason: '把加入行为直接等同成功结果，误导性强。',
    exampleScenario: '欢迎新人或讲事业时。',
  },
  {
    id: 'company-2',
    riskPhrase: '这是最好的创业捷径',
    recommendedPhrase: '这是一条适合从学习和自用开始的成长路径',
    riskLevel: 'medium',
    category: 'company',
    reason: '“捷径”暗示过低难度和过高确定性。',
    exampleScenario: '讲平台定位时。',
  },
  {
    id: 'company-3',
    riskPhrase: '老师讲的都是真的不用怀疑',
    recommendedPhrase: '建议结合系统资料、课程和自己的理解一起判断',
    riskLevel: 'medium',
    category: 'company',
    reason: '压制判断、放大权威，不利于合规沟通。',
    exampleScenario: '引导别人听会时。',
  },
]

export const complianceCategoryMeta = {
  product: { title: '产品表达', color: '#805AD5' },
  income: { title: '收益表达', color: '#E53E3E' },
  case: { title: '案例表达', color: '#D69E2E' },
  company: { title: '公司与机会表达', color: '#1A365D' },
  medical: { title: '医疗高风险表达', color: '#C53030' },
} as const
