export const productCatalog = [
  {
    slug: 'gnakg',
    icon: '🧬',
    name: 'GnAKG',
    subtitle: '细胞能量支持',
    description: '围绕细胞能量代谢与年轻态管理进行介绍，适合新人做基础产品认知。',
    color: '#805AD5',
    gradient: 'linear-gradient(135deg, #805AD5 0%, #B794F4 100%)',
    keyBenefits: ['支持活力状态', '关注能量管理', '支持代谢平衡'],
  },
  {
    slug: 'gncell',
    icon: '🔬',
    name: 'GnCELL',
    subtitle: '细胞健康支持',
    description: '聚焦细胞修复与状态管理，强调支持性表达与合规边界。',
    color: '#38A169',
    gradient: 'linear-gradient(135deg, #38A169 0%, #68D391 100%)',
    keyBenefits: ['支持细胞修复', '关注炎症管理', '支持恢复节奏'],
  },
  {
    slug: 'gn-hormone',
    icon: '⚖️',
    name: 'GN 荷尔蒙',
    subtitle: '内分泌平衡支持',
    description: '用于睡眠、情绪和精力管理相关的支持性沟通场景。',
    color: '#ED8936',
    gradient: 'linear-gradient(135deg, #ED8936 0%, #F6AD55 100%)',
    keyBenefits: ['支持睡眠质量', '关注情绪稳定', '支持平衡状态'],
  },
  {
    slug: 'gn-brain',
    icon: '🧠',
    name: 'GN 大脑',
    subtitle: '认知营养支持',
    description: '用于专注力、记忆力与脑力状态支持相关的基础分享。',
    color: '#3182CE',
    gradient: 'linear-gradient(135deg, #3182CE 0%, #63B3ED 100%)',
    keyBenefits: ['支持专注力', '支持记忆表现', '关注脑力状态'],
  },
]

export const productScienceTopics = [
  { icon: '🧬', title: 'DNA 修复支持', desc: '从细胞稳定性与修复能力理解健康管理。' },
  { icon: '⚡', title: 'NAD+ 与能量', desc: '解释细胞能量生成与活力状态的关系。' },
  { icon: '📊', title: '代谢平衡', desc: '关注状态管理，不做疗效承诺。' },
  { icon: '🧠', title: '认知营养', desc: '支持大脑与神经系统的营养逻辑。' },
  { icon: '🛡️', title: '炎症管理', desc: '解释身体状态维护与恢复支持。' },
  { icon: '😴', title: '睡眠支持', desc: '建立睡眠与精力管理的表达框架。' },
]
